name: compile-source
run-name: compiling source files

on: [push]

jobs:
  build:
    name: compile-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: npm install, compile, build
        run: |
          npm install
          npm run compile
          npm run build-firefox
          npm run build-chromium
          npm run build-opera
#     - name: Archive production artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: dist
#         path: dist
      - name: Build release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: mark_my_search-*.zip
      - name: Repository Pages dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: searchmarkers/searchmarkers.github.io
          event-type: update
