name: Compile Source
run-name: ${{ github.actor }} is compiling source files

on: [push]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: npm install, build, and test
      run: |
        npm install
        npm run compile
        npm run build-firefox
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: mark_my_search-*.zip
